import { GlobalResponse } from "../GlobalResponse";

export interface GetAdmissionDetailResponse extends GlobalResponse {
    admission_type: string,
    admission_sub_type: string,
    admission_no: string,
    patient_name: string,
    id_no: string,
    patient_id: number,
    address: string,
    city_id: string,
    city_name: string,
    dob: string,
    admission_date: string,
    payer_id_no: string,
    eligibility_no: string,
    primary_doctor: string,
    primary_doctor_user_id: number,
    email: string,
    contact_no: string,
    bed: string,
    age?: number,
    discharge_date: string,
    notes: string,
    mr_no: number,
    patient_type_id: number,
    patient_type: string,
    payer_id: number,
    payer_name: string,
    sex: string,
    class_name: string,
    class_id?: number,
    class_type_id?: number,
    class_type_name?: string,
    admission_sub_discharge_id?: number,
    admission_status_id: number,
    discharge_id? :number
    discharge_request_id: number
    discharge_type_id? :number
    discharge_type_name: string
    discharge_condition_id?: number
    discharge_condition_name: string
    discharge_plan_type_id: number
    discharge_plan_type_name: string
    discharge_request_status_id: number
    discharge_request_status_name: string
    triage_type: string
    triage_type_id: number
    triage_type_name: string
    item_to_return_exist: number
    is_item_to_return_exist?: boolean
    is_discharge_prescription_exist? :boolean
    payer_eligibility_id: string
    ar_invoice_id: string
    invoice_date: string
    payer_info: string
    national_id_type_id?: number
    national_id_type_name: string
    national_id_type_local_name: string
    discharge_user_name: string
}
