import { GlobalResponse } from "../GlobalResponse";

export interface GetInvoiceResponse extends GlobalResponse {
    ar_invoice_no: string,
    invoice_date: string,
    organization_id: number,
    invoice_gross_amount: number,
    patient_gross_amount: number,
    payer_gross_amount: number,
    payer_admin_fee: number,
    patient_admin_fee: number,
    invoice_admin_fee: number,
    payer_limit_numeric_factor: number,
    payer_limit_type_id: number,
    payer_limit_type_name: string,
    payer_limit_amount: number,
    patient_limit_amount: number,
    payer_discount_type_id: number,
    payer_discount_type_name: string,
    payer_discount_numeric_factor: number,
    patient_discount_type_id: number,
    patient_discount_type_name: string,
    patient_discount_numeric_factor: number,
    payer_discount_amount: number,
    patient_discount_amount: number,
    invoice_discount_amount: number,
    payer_net_amount: number,
    patient_net_amount: number,
    invoice_net_amount: number,
    payer_balance_amount: number,
    patient_balance_amount: number,
    invoice_balance_amount: number,
    invoice_round_amount: number
}