export interface MedicalOrderTransaction{
    admission_no: string,
    admission_id: number,
    org_id: number,
    patient_id: number,
    encounter_id: number,
    order_date: string,
    future_order_date: string,
    future_order_time: string,
    quantity: number,
    doctor_id: string,
    doctor_name: string,
    sales_item_id: number,
    sales_item_name: string,
    sales_item_type: string,
    sales_item_type_id: number,
    is_process: boolean,
    cpoe_trans_id: string,
    item_type: string,
    start_date: string,
    end_date: string,
    is_cito: number,
    checked?: boolean;
}